# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61b07672a9141813435605d6e718a25ff370bb41e87171cf57a98b766370c7b5d4222c79b6125d5b34e8df2cd98fd443b5f99be9d0ed33009cce97e175875931

test:
  secret_key_base: 8f439aa63814bf44b114027ef8361bbc86eeb5619b3ff2b134dae6073678a9fce3b6036c9f4ecbcabeb4df4ac41b0ccfc8afe75bb41e129dd4df764507399b46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
